// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sluqfpaxthqunolxobrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdXFmcGF4dGhxdW5vbHhvYnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzI1OTYsImV4cCI6MjA1OTgwODU5Nn0.RTFmFBX3RU7QLHfUNRdnhhWnU5JPEJSzcHJWyyTVoGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);